export const ALL_MODELS = [
  'gemini-2.5-pro',
  'gemini-3-pro-preview',
  'deepseek-reasoner',
  'gpt-5.2',
  'gpt-5.3-codex',
  'gpt-5.2-codex',
  'gpt-5.1-codex-max',
  'gpt-5.1-codex',
  'gpt-5.1-codex-mini',
  'gpt-5.1',
  'claude-sonnet-4-6',
  'claude-opus-4-6',
  'claude-haiku-4-5',
] as const
